# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    env_file:
      - secrets/postgres.env
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  hub:
    depends_on:
      - hub-db
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
      #- "/home/pmdadmin/git-repositories/jupyterhub-docker-deployment/data/ubuntu-on-docker/shadow:/etc/shadow:ro"
      #- "/home/pmdadmin/git-repositories/jupyterhub-docker-deployment/data/ubuntu-on-docker/passwd:/etc/passwd:ro"
      - "/home/pmdadmin/git-repositories/simple-jupyterhub-docker-deployment/images.json:/srv/jupyterhub/images.json:ro"
      - "/home/pmdadmin/git-repositories/jupyterhub-docker-deployment/data/certbot/conf/live/pyiron.material-digital.de/fullchain.pem:/srv/jupyterhub/secrets/jupyterhub.crt:ro"
      - "/home/pmdadmin/git-repositories/jupyterhub-docker-deployment/data/certbot/conf/live/pyiron.material-digital.de/privkey.pem:/srv/jupyterhub/secrets/jupyterhub.key:ro"

        #   ports:
        #- "443:443"
    links:
      - hub-db
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db
    env_file:
      - secrets/hub.env
      - secrets/postgres.env
      - secrets/oauth.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    name: ${DATA_VOLUME_HOST}
    external: true
  db:
    name: ${DB_VOLUME_HOST}
    external: true

networks:
  default:
    external: true
    name: cert_network
